name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'UmsatzsteuerApp_Monorepo_Starter/frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'UmsatzsteuerApp_Monorepo_Starter/frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch: {}

# PRs brauchen keine Schreibrechte für Pages
permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine FRONTEND_DIR
        id: detect
        run: |
          if [ -f "frontend/package.json" ]; then
            echo "FRONTEND_DIR=frontend" >> $GITHUB_ENV
            echo "Using frontend dir: frontend"
          elif [ -f "UmsatzsteuerApp_Monorepo_Starter/frontend/package.json" ]; then
            echo "FRONTEND_DIR=UmsatzsteuerApp_Monorepo_Starter/frontend" >> $GITHUB_ENV
            echo "Using frontend dir: UmsatzsteuerApp_Monorepo_Starter/frontend"
          else
            echo "Konnte kein frontend/package.json finden." >&2
            exit 1
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ${{ env.FRONTEND_DIR }}/package-lock.json

      - name: Install deps
        working-directory: ${{ env.FRONTEND_DIR }}
        run: npm ci || npm i

      - name: Build
        working-directory: ${{ env.FRONTEND_DIR }}
        run: npm run build

      - name: Add .nojekyll
        run: touch "${{ env.FRONTEND_DIR }}/dist/.nojekyll"

      - name: SPA 404 fallback
        working-directory: ${{ env.FRONTEND_DIR }}/dist
        run: cp index.html 404.html || true

      # Artifact nur bei push (PR braucht es nicht)
      - name: Upload artifact
        if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.FRONTEND_DIR }}/dist

  deploy:
    # Deploy NUR bei push auf main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
