name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'   # <- exakt dieser Pfad
  workflow_dispatch: {}  # erlaubt manuelles Starten

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # zur Übersicht: Verzeichnisbaum ausgeben
      - name: Debug repo tree
        run: |
          pwd
          ls -la
          echo "----"
          ls -la UmsatzsteuerApp_Monorepo_Starter || true
          echo "----"
          ls -la frontend || true

      # 🔎 Frontend-Verzeichnis automatisch ermitteln
      - name: Determine FRONTEND_DIR
        id: detect
        run: |
          if [ -f "frontend/package.json" ]; then
            echo "FRONTEND_DIR=frontend" >> $GITHUB_ENV
          elif [ -f "UmsatzsteuerApp_Monorepo_Starter/frontend/package.json" ]; then
            echo "FRONTEND_DIR=UmsatzsteuerApp_Monorepo_Starter/frontend" >> $GITHUB_ENV
          else
            echo "Konnte kein frontend/package.json finden." >&2
            exit 1
          fi
          echo "Using frontend dir: ${FRONTEND_DIR}"

      # Node mit Cache für stabile/schnelle Builds
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ env.FRONTEND_DIR }}/package-lock.json

      - name: Install deps
        working-directory: ${{ env.FRONTEND_DIR }}
        run: npm ci || npm i

      - name: Build
        working-directory: ${{ env.FRONTEND_DIR }}
        run: npm run build

      # SPA-Fallback: Deep-Links auf Client-Routen funktionieren
      - name: SPA 404 fallback
        working-directory: ${{ env.FRONTEND_DIR }}/dist
